version: "3.7"

services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: nft-rental-client
    container_name: nft-rental-react-client
    command: yarn start
    volumes:
      - ./website/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
